name: showcase
description: A new Flutter package for the Showcase feature.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.13.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Local Packages
  config:
    path: ../../config
  core:
    path: ../../core
  shared:
    path: ../../shared

  # State Management
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_lints: ^6.0.0
