name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  analyze-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Create Firebase Options
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: |
          mkdir -p packages/core/lib/firebase
          echo "$FIREBASE_OPTIONS_DART" > packages/core/lib/firebase/firebase_options.dart

      - name: Create Env Files
        env:
          ENV_STG: ${{ secrets.ENV_STG }}
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          echo "$ENV_STG" > .env.stg
          echo "$ENV_PROD" > .env.prod

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Code Generation
        run: dart run build_runner build

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Code
        run: flutter analyze
