name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Create Placeholder Env Files
        run: |
          touch .env.stg
          touch .env.prod

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Code Generation
        run: dart run build_runner build

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test
