name: Deploy Production

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-android-prod:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'v') && endsWith(github.head_ref, '-mobile-prod-release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Create Firebase Options
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: |
          mkdir -p lib/core/firebase
          echo "$FIREBASE_OPTIONS_DART" > lib/core/firebase/firebase_options.dart

      - name: Create Env Files
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          touch .env.stg
          echo "$ENV_PROD" > .env.prod

      - name: Create Google Services Json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: android

      - name: Create Service Account Key File
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > "$GITHUB_WORKSPACE/firebase_credentials.json"

      - name: Run Fastlane Android
        env:
          FIREBASE_APP_ID_ANDROID_PROD: ${{ secrets.FIREBASE_APP_ID_ANDROID_PROD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$GITHUB_WORKSPACE/firebase_credentials.json"
          cd android
          bundle exec fastlane distribute_prod

  deploy-ios-prod:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'v') && endsWith(github.head_ref, '-mobile-prod-release')
    runs-on: macos-14
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Create Firebase Options
        env:
          FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: |
          mkdir -p lib/core/firebase
          echo "$FIREBASE_OPTIONS_DART" > lib/core/firebase/firebase_options.dart

      - name: Create Env Files
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          touch .env.stg
          echo "$ENV_PROD" > .env.prod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          working-directory: ios

      - name: Create Service Account Key File
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > "$GITHUB_WORKSPACE/firebase_credentials.json"

      - name: Run Fastlane iOS
        env:
          FIREBASE_APP_ID_IOS_PROD: ${{ secrets.FIREBASE_APP_ID_IOS_PROD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$GITHUB_WORKSPACE/firebase_credentials.json"
          cd ios
          bundle exec fastlane distribute_prod
